controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # joint_trajectory_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController

    effort_controllers:
      type: effort_controllers/JointGroupEffortController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - cart_joint
    # interface_name: position
    interface_name: effort
    command_interfaces:
      # - position
      - effort
    state_interfaces:
      - position
      - velocity
      - effort